### PR TITLE
Refactor Dockerfile - see description

### PR DESCRIPTION
**Pull request by shymega**
- Use Debian Bullseye as `base` image.
- Use proper `LABEL` for authors/maintainers.
- Multi-stage builds.
- Download Rust via rustup.
- Combine RUN commands to reduce layers.

### CODE REVIEW

**Comment by shymega** [comment]
We can also use GitHub Actions to run the Makefile in this container image on a runner, and test build the codebase against PRs and commits on mainline.

**Comment by ThatcherC** [comment]
I get an error on this when I use the `./start_dev.sh` script:

```shell
OpenPineBuds$ ./start_dev.sh 
Creating openpinebuds_builder_run ... done
/bin/bash: /bin/bash: cannot execute binary file
ERROR: 126
```

I opened a PR (https://github.com/open-morphs/OpenPineBuds/pull/1) on your branch to address that! Works great for me now. Will removing the `ENTRYPOINT` line affect anything else?

**Comment by ThatcherC** [comment]
Actually another option is to delete the `command: /bin/bash` line in `docker-compose.yml` - that might be cleaner. What do you think?

**Comment by shymega** [comment]
It's weird, because I got this same error on my NixOS system. I thought maybe it was the ld-linux loader, but I wasn't sure. Maybe Debian puts bash in a different directory...

**Comment by shymega** [comment]
Ah, OK - so it's just the docker/podman-compose. I'll merge #2, as we should allow the Docker image to run with bash when run interactively, and this way allows us to keep that functionality. Cheer for the MR.

**Pull request merged**
