### PR TITLE
Developer comforts

### PR DESCRIPTION
**Pull request by Ralim**
* Adds CI step to build firmware in github
* Sets up clang-format for LLVM style
* Runs said clang-format over the entire repository
* Fixes a _lot_ of header file includes being missing after this

I have flashed this to my buds and all looks to work so far 😁

### CODE REVIEW

**Comment by Ralim** [comment]
Notification to @ThatcherC 

I dont expect anyone to actually read this PR (250k lines is stupid).
But you may want to check commit-by-commit the first few.

Or tell me if I've done something grossly wrong 😁

**Comment by ThatcherC** [comment]
This is great! The formatted stuff looks nice. The one issue I'm having is that the `clang-format` command doesn't work for me in the Dockerfile. Any idea why that would be? It's confusing because I see the clang-format installation in the Dockerfile...

**Comment by Ralim** [comment]
Did you re-run the docker build?
It does work for me when I was testing yesterday 😓

**Comment by ThatcherC** [comment]
Oh yup that was it! Just had to delete the old docker images and rebuild. Nice to have that merged!

**Comment by Ralim** [comment]
`docker-compose build` will also run a build re-using what layers it can for future reference :)

**Pull request merged**
