### PR TITLE
Fixup build on modern gcc

### PR DESCRIPTION
**Pull request by neochapay**

### CODE REVIEW

**Comment by Ralim** [comment]
This is excellent, have you tested flashing after build and all features working ?

Which modern gcc did you use ?

**Comment by neochapay** [comment]
> This is excellent, have you tested flashing after build and all features working ?

I'm scared. I only have one buds ^_^

> Which modern gcc did you use ?

gcc version 11.3.0 (Ubuntu 11.3.0-1ubuntu1~22.04)

**Comment by Ralim** [comment]
Thats fair enough; happy to do the testing here.

Sad to report that while this does make the build work; the resulting file wont run on the buds. They just refuse to boot the program.

I'm suspect that something changes the start of the file that the bootloader is looking at to decide if it starts the file or not.
That is my guess though (not certain; have not dug into it)

**Comment by shymega** [comment]
I'm not sure what the issue is here either. Maybe it's specific to your buds, @Ralim?

I would test this PR myself, but I don't have any buds yet.

I'm looking to base my PR for conversion to CMake on this PR. So if we could rebase it against mainline, that'd be great. Or I could do that, and push, if I had access (not that I'm asking for it, but I'd be happy to rebase this PR against main and get it ready for testing).

Cheers.

**Comment by Ralim** [comment]
@shymega 
This is not buds specific sadly and should not be used as a base.
It will need time to investigate which of the precisely placed structures is being moved into a bad location or optimised out.

Would basically need to make build as deterministic as possible then run it on both compilers and compare the output section by section to find it.

In the past when I ran into this, cleaning up the compiler chain helped flush out the quirks that caused these issues.

**Comment by shymega** [comment]
@neochapay I want to get your opinion on something. I opened #55 because I didn't want to mess up your PR, but it messes the tracker.

Do you mind if we force-push your PR to fix the merge conflicts? I'm not keen on opening yet another PR to rebase.

I am looking forward to your response.

**Comment by neochapay** [comment]
@shymega i was update and fix all conflicts

**Comment by shymega** [comment]
@neochapay Thanks. However, my query was more relating to whenever we, maintainers, can edit your PR. I see we can push, but I want to get your explicit approval.

**Comment by shymega** [comment]
Rebased against main.

@Ralim Can we get this merged once tests pass?

**Review by Ralim — APPROVED** [review]

**Pull request merged**
