### PR TITLE
Fix build on modern GCC (rebased, follow-up on #26).

### PR DESCRIPTION
**Pull request by shymega**
So, this is a new PR on the advice of @Ralim, and I've rebased it against mainline. Also added a commit to keep the `#define`s in consistency with the rest of the codebase.

It might even fix the issue we're facing. Needs testing. I have a set of PineBuds being shipped by Pine very soon...

Closes #26.

### CODE REVIEW

**Comment by Ralim** [comment]
Sadly I have to report this doesnt fix issues running it on gcc >9.
Tested GCC 10,11,12 with no dice.

Havent had time to dig into why just yet though. But wanted to let you know asap.

**Comment by Ralim** [comment]
I'll double check this doesnt break anything on GCC 9 and if so merge it; since then its at least cleaner

**Comment by shymega** [comment]
If we did merge this, would it break existing CI build artefacts? I'm of the position that we should try and get it working first with GCC v9+, then merge.

**Comment by shymega** [comment]
After @neochapay's recent rebase, we can close this PR for now: https://github.com/pine64/OpenPineBuds/pull/26#issuecomment-1794239211

**Pull request closed without merging**
